// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: bindings.sql

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BatchCreateRestaurantBindingParams struct {
	ID                 pgtype.UUID
	GlovoRestaurantID  pgtype.UUID
	YandexRestaurantID pgtype.UUID
}
