// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: copyfrom.go

package database

import (
	"context"
)

// iteratorForBatchCreateDishBindings implements pgx.CopyFromSource.
type iteratorForBatchCreateDishBindings struct {
	rows                 []BatchCreateDishBindingsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchCreateDishBindings) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchCreateDishBindings) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].RestaurantBindingID,
		r.rows[0].GlovoDishID,
		r.rows[0].YandexDishID,
	}, nil
}

func (r iteratorForBatchCreateDishBindings) Err() error {
	return nil
}

func (q *Queries) BatchCreateDishBindings(ctx context.Context, arg []BatchCreateDishBindingsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"dish_binding"}, []string{"id", "restaurant_binding_id", "glovo_dish_id", "yandex_dish_id"}, &iteratorForBatchCreateDishBindings{rows: arg})
}

// iteratorForBatchCreateGlovoDishes implements pgx.CopyFromSource.
type iteratorForBatchCreateGlovoDishes struct {
	rows                 []BatchCreateGlovoDishesParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchCreateGlovoDishes) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchCreateGlovoDishes) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Name,
		r.rows[0].Description,
		r.rows[0].Price,
		r.rows[0].DiscountedPrice,
		r.rows[0].GlovoApiDishID,
		r.rows[0].GlovoRestaurantID,
		r.rows[0].CreatedAt,
		r.rows[0].UpdatedAt,
	}, nil
}

func (r iteratorForBatchCreateGlovoDishes) Err() error {
	return nil
}

func (q *Queries) BatchCreateGlovoDishes(ctx context.Context, arg []BatchCreateGlovoDishesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"glovo_dish"}, []string{"id", "name", "description", "price", "discounted_price", "glovo_api_dish_id", "glovo_restaurant_id", "created_at", "updated_at"}, &iteratorForBatchCreateGlovoDishes{rows: arg})
}

// iteratorForBatchCreateGlovoRestaurants implements pgx.CopyFromSource.
type iteratorForBatchCreateGlovoRestaurants struct {
	rows                 []BatchCreateGlovoRestaurantsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchCreateGlovoRestaurants) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchCreateGlovoRestaurants) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Name,
		r.rows[0].Address,
		r.rows[0].DeliveryFee,
		r.rows[0].PhoneNumber,
		r.rows[0].GlovoApiStoreID,
		r.rows[0].GlovoApiAddressID,
		r.rows[0].GlovoApiSlug,
		r.rows[0].CreatedAt,
		r.rows[0].UpdatedAt,
	}, nil
}

func (r iteratorForBatchCreateGlovoRestaurants) Err() error {
	return nil
}

func (q *Queries) BatchCreateGlovoRestaurants(ctx context.Context, arg []BatchCreateGlovoRestaurantsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"glovo_restaurant"}, []string{"id", "name", "address", "delivery_fee", "phone_number", "glovo_api_store_id", "glovo_api_address_id", "glovo_api_slug", "created_at", "updated_at"}, &iteratorForBatchCreateGlovoRestaurants{rows: arg})
}

// iteratorForBatchCreateRestaurantBinding implements pgx.CopyFromSource.
type iteratorForBatchCreateRestaurantBinding struct {
	rows                 []BatchCreateRestaurantBindingParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchCreateRestaurantBinding) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchCreateRestaurantBinding) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].GlovoRestaurantID,
		r.rows[0].YandexRestaurantID,
	}, nil
}

func (r iteratorForBatchCreateRestaurantBinding) Err() error {
	return nil
}

func (q *Queries) BatchCreateRestaurantBinding(ctx context.Context, arg []BatchCreateRestaurantBindingParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"restaurant_binding"}, []string{"id", "glovo_restaurant_id", "yandex_restaurant_id"}, &iteratorForBatchCreateRestaurantBinding{rows: arg})
}

// iteratorForBatchCreateYandexDishes implements pgx.CopyFromSource.
type iteratorForBatchCreateYandexDishes struct {
	rows                 []BatchCreateYandexDishesParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchCreateYandexDishes) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchCreateYandexDishes) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Name,
		r.rows[0].Description,
		r.rows[0].Price,
		r.rows[0].DiscountedPrice,
		r.rows[0].YandexRestaurantID,
		r.rows[0].YandexApiID,
		r.rows[0].CreatedAt,
		r.rows[0].UpdatedAt,
	}, nil
}

func (r iteratorForBatchCreateYandexDishes) Err() error {
	return nil
}

func (q *Queries) BatchCreateYandexDishes(ctx context.Context, arg []BatchCreateYandexDishesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"yandex_dish"}, []string{"id", "name", "description", "price", "discounted_price", "yandex_restaurant_id", "yandex_api_id", "created_at", "updated_at"}, &iteratorForBatchCreateYandexDishes{rows: arg})
}

// iteratorForBatchCreateYandexRestaurants implements pgx.CopyFromSource.
type iteratorForBatchCreateYandexRestaurants struct {
	rows                 []BatchCreateYandexRestaurantsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchCreateYandexRestaurants) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchCreateYandexRestaurants) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Name,
		r.rows[0].Address,
		r.rows[0].DeliveryFee,
		r.rows[0].PhoneNumber,
		r.rows[0].YandexApiSlug,
		r.rows[0].CreatedAt,
		r.rows[0].UpdatedAt,
	}, nil
}

func (r iteratorForBatchCreateYandexRestaurants) Err() error {
	return nil
}

func (q *Queries) BatchCreateYandexRestaurants(ctx context.Context, arg []BatchCreateYandexRestaurantsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"yandex_restaurant"}, []string{"id", "name", "address", "delivery_fee", "phone_number", "yandex_api_slug", "created_at", "updated_at"}, &iteratorForBatchCreateYandexRestaurants{rows: arg})
}
