// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DishBinding struct {
	ID          pgtype.UUID
	GlovoDishID pgtype.UUID
}

type GlovoDish struct {
	ID                pgtype.UUID
	Name              string
	Description       string
	Price             pgtype.Numeric
	Discount          pgtype.Numeric
	GlovoApiDishID    int32
	GlovoRestaurantID pgtype.UUID
	CreatedAt         pgtype.Timestamp
	UpdatedAt         pgtype.Timestamp
}

type GlovoRestaurant struct {
	ID                pgtype.UUID
	Name              string
	Address           string
	DeliveryFee       pgtype.Numeric
	PhoneNumber       pgtype.Text
	GlovoApiStoreID   int32
	GlovoApiAddressID int32
	GlovoApiSlug      string
	CreatedAt         pgtype.Timestamp
	UpdatedAt         pgtype.Timestamp
}

type RestaurantBinding struct {
	ID                pgtype.UUID
	GlovoRestaurantID pgtype.UUID
}
