// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: yandex.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BatchCreateYandexRestaurantsParams struct {
	ID            pgtype.UUID
	Name          string
	Address       pgtype.Text
	DeliveryFee   pgtype.Numeric
	PhoneNumber   pgtype.Text
	YandexApiSlug string
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

const getYandexFilters = `-- name: GetYandexFilters :many
SELECT name FROM yandex_filters
`

func (q *Queries) GetYandexFilters(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getYandexFilters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getYandexRestaurant = `-- name: GetYandexRestaurant :one
select id, name, address, delivery_fee, phone_number, yandex_api_slug, created_at, updated_at from yandex_restaurant limit 1
`

func (q *Queries) GetYandexRestaurant(ctx context.Context) (YandexRestaurant, error) {
	row := q.db.QueryRow(ctx, getYandexRestaurant)
	var i YandexRestaurant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.DeliveryFee,
		&i.PhoneNumber,
		&i.YandexApiSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getYandexRestaurantSlugs = `-- name: GetYandexRestaurantSlugs :many
SELECT yandex_api_slug FROM yandex_restaurant
`

func (q *Queries) GetYandexRestaurantSlugs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getYandexRestaurantSlugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var yandex_api_slug string
		if err := rows.Scan(&yandex_api_slug); err != nil {
			return nil, err
		}
		items = append(items, yandex_api_slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
